backend/myproject/courses/urls.py
from django.urls import include, path, re_path
import courses.views as courses
from courses import views

app_name = 'courses'

urlpatterns = [

    path('', courses.CourseListView.as_view(), name='index'),
    path('course/create/', courses.CourseCreateView.as_view(),
         name='course_create'),
    path('course/detail/<int:pk>/',
         courses.CourseDetailView.as_view(),
         name='course'),
    path('course/update/<int:pk>/',
         courses.CourseUpdateView.as_view(),
         name='course_update'),
    path('course/delete/<int:pk>/',
         courses.CourseDeleteView.as_view(),
         name='course_delete'),
    path('course/contact/', views.contactform, name='contact'),
    path('course/goodsend/', views.goodsend, name='goodsend'),
    ]

backend/myproject/myproject/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from graphene_django.views import GraphQLView

from .schema import schema

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls', namespace='courses')),
    path('django-rq/', include('django_rq.urls')),
    path('coursesapi/user/', include('userapi.urls')),
    path('coursesapi/', include('coursesapi.urls')),
    path("graphql/", GraphQLView.as_view(graphiql=True, schema=schema)),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

backend/myproject/templates/root.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
            Otus Courses
        {% endblock %}
    </title>

    {% block css %}
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    {% endblock %}

    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock %}
</head>

<body>
<div class="wrapper">
    {% block header %}
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="margin:24px 0;">
                <a class="navbar-brand" href="{% url 'courses:index' %}">Otus Courses</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
                        data-target="#navb">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navb">
                    <ul class="navbar-nav mr-auto">
                        {% block main_menu %}{% endblock %}
                    </ul>
                </div>
            </nav>
        </header>
    {% endblock %}

    <div class="main_container">
        {% block breadcrumb %}
        {% endblock %}

        {% block content %}
        {% endblock %}
    </div>
</div>
</body>

</html>