backend/myproject/courses/urls.py
from django.urls import include, path, re_path
import courses.views as courses
from courses import views

app_name = 'courses'

urlpatterns = [

    path('', courses.CourseListView.as_view(), name='index'),
    path('course/create/', courses.CourseCreateView.as_view(),
         name='course_create'),
    path('course/detail/<int:pk>/',
         courses.CourseDetailView.as_view(),
         name='course'),
    path('course/update/<int:pk>/',
         courses.CourseUpdateView.as_view(),
         name='course_update'),
    path('course/delete/<int:pk>/',
         courses.CourseDeleteView.as_view(),
         name='course_delete'),
    path('course/contact/', views.contactform, name='contact'),
    path('course/goodsend/', views.goodsend, name='goodsend'),
    ]

backend/myproject/myproject/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from graphene_django.views import GraphQLView

from .schema import schema

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls', namespace='courses')),
    path('django-rq/', include('django_rq.urls')),
    path('coursesapi/user/', include('userapi.urls')),
    path('coursesapi/', include('coursesapi.urls')),
    path("graphql/", GraphQLView.as_view(graphiql=True, schema=schema)),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

backend/myproject/courses/models.py
from datetime import date

from django.contrib.auth.models import User
from django.db import models


class PersonMixin(models.Model):
    SEX_MAN = 0
    SEX_WOMAN = 1
    SEX_CHOICES = (
    (SEX_MAN, 'Man'),
    (SEX_WOMAN, 'Woman')
    )
    sex = models.PositiveSmallIntegerField(choices=SEX_CHOICES, default=0)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    date_of_birth = models.DateField(blank=True, default=date.today)
    city = models.CharField(max_length=50, null=True, default="Moscow")

    class Meta:
        abstract = True


class Teacher(PersonMixin):
    bio = models.CharField(max_length=1000)

    @property
    def full_name(self):
        return f'{self.user.first_name} {self.user.last_name}'

    def __str__(self):
        return self.full_name


class Student(PersonMixin):

    @property
    def full_name(self):
        return f'{self.user.first_name} {self.user.last_name}'

    def __str__(self):
        return self.full_name


class Course(models.Model):
    title = models.CharField(max_length=50)
    teacher = models.ForeignKey(Teacher, on_delete=models.SET_NULL, null=True, related_name="course")
    students = models.ManyToManyField(Student, related_name="course",)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class Lesson(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=50, blank=True)
    date = models.DateField(blank=True, default=date.today)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="lesson")

    def __str__(self):
        return self.title

backend/myproject/courses/forms.py
from django import forms

from courses.models import Course, Lesson


class BlogBaseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class LessonForm(BlogBaseForm):
    class Meta:
        model = Lesson
        fields = '__all__'


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'size':'40','class': 'form-control'}))
    sender = forms.EmailField(widget=forms.TextInput(attrs={'size':'40','class': 'form-control'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))
    copy = forms.BooleanField(required=False)

backend/myproject/courses/views.py
import time

from django.contrib import auth
from django.core.mail import BadHeaderError, send_mail
from django.db import transaction
from django.forms import inlineformset_factory
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView, DeleteView, DetailView, ListView, UpdateView)
from django_rq import job

from courses.forms import ContactForm, LessonForm
from courses.models import Course, Lesson
from courses.scheduler import send_mail_scheduler
from courses.tasks import send_mail_job


class CourseListView(ListView):
    model = Course

    def get_queryset(self):
        return self.model.objects.filter(is_active=True)


class CourseCreateView(CreateView):
    model = Course
    success_url = reverse_lazy('courses:index')
    fields = '__all__'


class CourseDetailView(DetailView):
    model = Course

    queryset = Course.objects.prefetch_related('user')


class CourseUpdateView(UpdateView):
    model = Course
    success_url = reverse_lazy('courses:index')
    fields = '__all__'

    def get_context_data(self, **kwargs):
            data = super().get_context_data(**kwargs)
            CourseFormSet = inlineformset_factory(Course, Lesson, form=LessonForm, extra=1)
            data['lesson_courses'] = CourseFormSet(self.request.POST or None, instance=self.object)
            return data

    def form_valid(self, form):
        context = self.get_context_data()
        lesson_courses = context['lesson_courses']

        with transaction.atomic():
            self.object = form.save()
            if lesson_courses.is_valid():
                lesson_courses.instance = self.object
                lesson_courses.save()

        return super().form_valid(form)


class CourseDeleteView(DeleteView):
    model = Course
    success_url = reverse_lazy('courses:index')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


def contactform(reguest):
    if reguest.method == 'POST':
        form = ContactForm(reguest.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            sender = form.cleaned_data['sender']
            message = form.cleaned_data['message']
            copy = form.cleaned_data['copy']
            recepients = ['owpdjangotest@gmail.com']
            if copy:
                recepients.append(sender)
            send_mail_scheduler(subject, message, 'owpdjangotest@gmail.com', recepients)
            return HttpResponseRedirect('/course/goodsend/')
    else:
        form = ContactForm()
    return render(reguest, 'courses/contact.html', {'form': form, 'username': auth.get_user(reguest).username})

def goodsend(reguest):
    goodsend = 'goodsend'
    return render(reguest, 'courses/goodsend.html', {'goodsend': goodsend})

backend/myproject/courses/templates/courses/base.html
{% extends 'root.html' %}
{% load static %}

{% block title %}
    {{ block.super }} / {{ title }}
{% endblock %}

{% block js %}
    {{ block.super }}
    <script src="{% static 'js/jquery.formset.js' %}"></script>
{% endblock %}

{% block main_menu %}
    {% include 'courses/inc/inc__main_menu.html' %}
{% endblock %}

backend/myproject/courses/templates/courses/contact.html
{% extends 'courses/base.html' %}
{% load static %}

{% block content %}
 <div class="panel panel-success">
  <div class="panel-heading">
    <h2 class="panel-title">Обратная связь</h2>
  </div>
  <div class="panel-body">
<div class="well well-lg">
    <h3></h3>
<form action="{% url 'courses:contact' %}" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
	<div>
	  <label for="id_subject">Тема:</label>
	  {{ form.subject.errors }}
      <input class="form-control" id="id_subject" name="subject" placeholder="Тема">
	</div>
    &nbsp;
	<div>
	  <label for="id_sender">E-mail:</label>
	  {{ form.sender.errors }}
      <input class="form-control" id="id_sender" name="sender" placeholder="Ваш e-mail">
	</div>
    &nbsp;
	<div>
	  <label for="id_message">Сообщение:</label>
	  {{ form.message.errors }}
      <textarea class="form-control" id="id_message" name="message" placeholder="Введите ваше сообщение"></textarea>
	</div>
    &nbsp;
	<div>
	  {{ form.copy.errors }}
	  <label for="id_copy">{{ form.copy }} Отправить копию себе </label>
	</div>
    <br>
	<input type="submit" class="btn btn-success" value="Отправить сообщение"/>
</form>
  </div>
</div>
</div>

{% endblock %}

backend/myproject/courses/templates/courses/course_confirm_delete.html
{% extends 'courses/base.html' %}
{% load static %}

{% block content %}
    <div class="course-record-delete-form">
        <form method="post">
            {% csrf_token %}
            <input type="submit" value="delete {{ object.title }}?">
        </form>
        <button>
            <a href="{% url 'courses:index' %}">cancel</a>
        </button>
    </div>
{% endblock %}

backend/myproject/courses/templates/courses/course_detail.html
{% extends 'courses/base.html' %}
{% load static %}

{% block content %}
    <div class="course-record">
        <h2>{{ course.title }}</h2>
        <h3>Teacher: {{ course.teacher }}</h3>
        <h4>Students: </h4>
        <p>{% for student in course.students.all %}{{ student }}</p>{% endfor %}
        <h4>Timetable</h4>
        {% for lesson in course.lesson.all %}
        <h5>Lesson:</h5>
        <p>{{ lesson.title }}</p>
        <p>{{ lesson.description }}</p>
        <p>Date: {{ lesson.date }}</p>
        {% endfor %}
    </div>
    <div class="links">
        <div class="link">
            <a href="{% url 'courses:course_update' course.pk %}">
                edit
            </a>
        </div>
        <div class="link">
            <a href="{% url 'courses:course_delete' course.pk %}">
                delete
            </a>
        </div>
    </div>
{% endblock %}

backend/myproject/courses/templates/courses/course_form.html
{% extends 'courses/base.html' %}
{% load static %}

{% block content %}
    <div class="course-record-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <table class="table">
                {{ lesson_courses.management_form }}
                {% for form in lesson_courses.forms %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                <th class="formset-td">
                                    {{ field.label|capfirst }}
                                </th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <tr class="formset-row">
                        {% for field in form.visible_fields %}
                            <td class="formset-td">
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {{ field }}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
            <input type="submit" value="save">
        </form>
    </div>
    <script>
        $('.formset-row').formset({
            addText: 'add lesson',
            deleteText: 'delete',
            prefix: 'lesson_courses',
        });
    </script>

{% endblock %}

backend/myproject/courses/templates/courses/course_list.html
{% extends 'courses/base.html' %}
{% load static %}

{% block content %}
    <h1>Сourse list</h1>
    <div class="courses-list">
        <ul>
            {% for course in object_list %}
                <li>
                    <a href="{% url 'courses:course' course.pk %}">
                        {{ course.title }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

backend/myproject/courses/templates/courses/goodsend.html
{% extends 'courses/base.html' %}
{% load static %}

{% block content %}

 <div class="panel panel-success">
  <div class="panel-heading">
    <h2 class="panel-title"></h2>
  </div>
  <div class="panel-body">
<div class="well well-lg" align="center">
    <h3>Спасибо, Ваше сообщение отправлено!</h3>
    <div align="center"><a href="/"><button type="button" class="btn">Вернутся на главную</button></a></div>
  </div>
</div>
</div>
{% endblock %}